services:
  - type: web
    name: slade-brewing
    runtime: python3
    startCommand: python server.py
    buildCommand: python --version
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: sladebrewing/sladebrewing
